name: Package addon

on:
  push:
    branches:
      - master
    tags:
      - '*'
      - '!**-classic'
      - '!**-rc**'
      - "!**-alpha**"
      - "!**-beta**"
    paths-ignore:
      - '.github/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout addon
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

#      - name: Run luacheck
#        uses: BigWigsMods/actions/luacheck@master
#        with:
#          args: -q

      - name: Package
        uses: BigWigsMods/packager@master
        env:
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
          WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
          GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
          WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}