name: Package beta addon

on:
  push:
    branches:
      - main
    tags:
      - "**-beta**"
      - "**-rc**"
    paths-ignore:
      - '.github/**'
      - '**/README.md'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout addon
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

#      - name: Run luacheck
#        uses: BigWigsMods/actions/luacheck@master
#        with:
#          args: -q

      - name: Package
        uses: BigWigsMods/packager@v2
        env:
#          CF_API_KEY: ${{ secrets.CF_API_KEY }}
#          WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
          GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
          WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}